---
- name: Install apt-get base
  apt: name={{ item }}  update_cache=yes
  become: True
  with_items:
  - python-dev
  - python-pip
  - libffi-dev
  - dpkg-dev
  - libssl-dev

- name: Upgrade pip
  pip: name={{item.name}} version={{item.version}}
  with_items:
    - {name: setuptools, version: 20.10.1}
    - {name: pip, version: 8.1.1}
  become: yes

- name: Upgrade pip again
  command: pip install -U pip
  become: yes

